v1 <- 1:5
v2 <- v1 + 3
v3 <- 1:6
v4 <- v3^2
v5 <- v4/2
caractere <- c("Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche")
caractere[c(2,7)]
vecteur <- c("True", "False", "False", "True", "False")
class(vecteur)
numerique <- c(1.5, 7.8, 3.2, 4.6, 5.4, 1.1)
class(numerique)
numerique[-3]
mois <- c("Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre")
class(mois)
mois[c(1,2,3)]
negatif <- c(-4, -7, -8, -3, -2, -4)
class(negatif)
negatif[c(6,1)]
fruit <- c("Orange", "Pomme", "Cerise", "Framboise", "Ananas")
class(fruit)
fruit[c(-1, -2)]
manquante <- c(4, 7, NA, 8, 3)
class(manquante)
sequence <- seq(1, 10)
length(sequence)
sequence <- seq(2, 20, 2)
length(sequence)
sequence <- seq(0, -5)
length(sequence)
sequence <- seq(5, 50, 5)
length(sequence)
sequence <- seq(10, 1)
length(sequence)
sequence <- seq(0, 1, 0.1)
length(sequence)
sequence <- seq(5, -5, -1)
length(sequence)
sequence <- seq(1, 10, 2)
length(sequence)
vecteur <- rep(3,5)
vecteur <- rep(c("A", "B", "C"), 3)
vecteur <- rep(1:3, 3)
vecteur <- rep(c("True", "False"), 4)
rm(vecteur)
vecteur <- runif(5, 0, 1)
mean(vecteur)
median(vecteur)
min(vecteur)
max(vecteur)
vecteur <- runif(10, -5, 5)
mean(vecteur)
median(vecteur)
min(vecteur)
max(vecteur)
vecteur <- runif(100, 10, 20)
vecteur <- runif(15, 50, 100)
echantillon <- rnorm(20,-2,3)
moyenne <- mean(echantillon)
ecart_type <- sd(echantillon)
print(paste("Moyenne : ", moyenne))
print(paste("Ecart-type : ", ecart_type))
hist(echantillon)
echantillon <- rnorm(2000,0,1)
moyenne <- mean(echantillon)
ecart_type <- sd(echantillon)
print(paste("Moyenne : ", moyenne))
print(paste("Ecart-type : ", ecart_type))
hist(echantillon)
quantile(echantillon, probs = c(0.25))
quantile(echantillon, probs = c(0.50))
quantile(echantillon, probs = c(0.75))
quantile(echantillon, probs = seq(0,1,0.1))
quantile(echantillon, probs = seq(0, 1, 0.01))